photoapp/urls.py
from django.urls import path
from .views import *


app_name="photoapp"
urlpatterns=[
	path("",HomeView.as_view(),name="home"),
	path("contact/",ContactView.as_view(),name="contact"),
	path("about/",AboutView.as_view(),name="about"),
	path("company/list/",CompanyListView.as_view(),name="companylist"),
	path("company/<int:pk>/detail/",CompanyDetailView.as_view(),name="companydetail"),
	path("laptop/<int:pk>/detail/",LaptopDetailView.as_view(),name="laptopdetail"),
	path("sendmail/",SendEmailView.as_view(),name="sendemail"),
	path("laptop/create/",LaptopCreateView.as_view(),name="laptopcreate"),
	path("register/",RegistrationView.as_view(),name="registration"),
	
	





]

photoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("photoapp.urls")),

]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

photoapp/models.py
from django.db import models

# Create your models here.


class Company(models.Model):
	title=models.CharField(max_length=200)
	logo=models.ImageField(upload_to="companies")
	description=models.TextField(null=True,blank=True)
	view_count=models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.title





class Laptop(models.Model):
	model_no=models.CharField(max_length=200)
	serial_no=models.CharField(max_length=50,unique=True)
	company=models.ForeignKey(Company,on_delete=models.CASCADE)
	processor=models.CharField(max_length=200)
	description=models.TextField(null=True,blank=True)
	image=models.ImageField(upload_to="laptops")
	view_count=models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.company.title+"-"+self.model_no



class Message(models.Model):
	sender=models.CharField(max_length=200)
	email=models.EmailField(null=True,blank=True)
	mobile=models.CharField(max_length=50)
	subject=models.CharField(max_length=200)
	text=models.TextField()
	date=models.DateTimeField(auto_now_add=True)


	def __str__(self):
		return self.sender

photoapp/forms.py
from django import forms

from .models import *


class MyForm(forms.Form):
	name=forms.CharField()
	email=forms.EmailField()
	company=forms.CharField()




class ContactForm(forms.Form):
	fullname=forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control",

		"placeholder":"Enter your full name",}))
	email=forms.EmailField(required=False,widget=forms.EmailInput(attrs={
		"class":"form-control",

		"placeholder":"Email",}))
	mobile=forms.CharField(widget=forms.NumberInput(attrs={
		"class":"form-control",

		"placeholder":"Phone number",}))
	subject=forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control",

		"placeholder":"Subject",}))
	message=forms.CharField(widget=forms.Textarea(attrs={
		"class":"form-control",

		"placeholder":"Type your message",
		"rows":5,

		}))





class LaptopForm(forms.ModelForm):
	class Meta:
		model=Laptop
		fields=["model_no",'serial_no','company','processor','description','image']



class RegistrationForm(forms.Form):
	email=forms.EmailField(widget=forms.EmailInput())
	password=forms.CharField(widget=forms.PasswordInput())
	confirm_password=forms.CharField(widget=forms.PasswordInput())


	def clean_confirm_password(self):
		pw=self.cleaned_data['password']
		c_pw=self.cleaned_data['confirm_password']
		if (pw !=c_pw):
			raise forms.ValidationError("Password did not match.")

		if (len(pw)<6):
			raise forms.ValidationError("Password too short")
		return c_pw


	def clean_email(self):
		eml=self.cleaned_data["email"]
		if eml=="abc@gmail.com":
			raise forms.ValidationError("Choose another Email")

		return eml

photoapp/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import *
from .models import *
from .forms import *
from django.core.mail import send_mail
from django.conf import settings

class HomeView(TemplateView):
	template_name="home.html"

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		# context["name"]="Madhav"
		# context["address"]="palpa"
		# context["student"]=["ram","hari","sita"]
		context["alllaptops"]=Laptop.objects.all()
		context["companies"]=Company.objects.all()
		return context



class ContactView(FormView):
	template_name="contact.html"
	form_class=ContactForm
	success_url="/"


	def form_valid(self,form):
		nam=form.cleaned_data["fullname"]
		eml=form.cleaned_data["email"]
		mbl=form.cleaned_data["mobile"]
		sub=form.cleaned_data['subject']
		message=form.cleaned_data['message']
		Message.objects.create(sender=nam,email=eml,mobile=mbl,subject=sub,text=message)

		return super().form_valid(form)



class AboutView(TemplateView):
	template_name="about.html"



class CompanyListView(ListView):
	template_name="companylist.html"
	queryset=Company.objects.all().order_by("-id")  #queryset API
	context_object_name="allcompanies"



class CompanyDetailView(DetailView):
	template_name="companydetail.html"
	queryset=Company.objects.all()     #model=Task
	context_object_name="companyobject"

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		cmp_id=self.kwargs["pk"]
		this_company=Company.objects.get(id=cmp_id)
		this_company.view_count +=1
		this_company.save()


		return context


class LaptopDetailView(DetailView):
	template_name="laptopdetail.html"
	queryset=Laptop.objects.all()     #model=Task
	context_object_name="laptopobject"

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		ltp_id=self.kwargs["pk"]
		this_laptop=Laptop.objects.get(id=ltp_id)
		this_laptop.view_count +=1
		this_laptop.save()


		return context



class SendEmailView(FormView):
	template_name="sendmail.html"
	form_class=MyForm
	success_url="/"

	def form_valid(self,form):
		a=form.cleaned_data["name"]
		b=form.cleaned_data["email"]
		c=form.cleaned_data["company"]
		# print(a,b,c)
		send_mail(
		"Quotion",
		"hii " +a+",we have got your message and will contact you soon",
		settings.EMAIL_HOST_USER,
		[b,"sangit.niroula@gmail.com",],
		fail_silently=False
			)
		print("message sent successfully")



		return super().form_valid(form)


class AboutView(TemplateView):
	template_name="about.html"





class LaptopCreateView(CreateView):
	template_name="laptopcreate.html"
	form_class=LaptopForm
	success_url="/"


class RegistrationView(FormView):
	template_name="register.html"
	form_class=RegistrationForm
	success_url="/"

templates/about.html
{% extends 'base.html' %}
{% block title %}
       	About
		{% endblock %}


{% block content %}
<h3>this is content of about page</h3>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<title>
		{% block title %}
		{% endblock %}
	</title>
</head>
<body>
<!-- <a href="/">Home</a>| -->
<a href="{% url 'photoapp:home' %}">Home</a>|
<a href="{% url 'photoapp:companylist' %}">Companies</a>|
<a href="{% url 'photoapp:sendemail' %}">Form</a>|
<a href="{% url 'photoapp:contact' %}">Contact-us</a>|
<a href="/laptop/create/">Create Laptop</a>|
<a href="{% url 'photoapp:registration' %}">Registration-Form</a>
<!-- <p>{{request.user}}</p> -->
<hr>


{% block content %}


{% endblock %}
</body>
</html>

templates/companydetail.html
{% extends "base.html" %}

{% block title %}
       	{{companyobject.title}}
		{% endblock %}




{% block content %}
<a href="/company/list/"><button style="color: red">Back</button></a><br>
<img src="{{companyobject.logo.url}}" width="200" >
<h3>{{companyobject.title}}(Viewed:{{companyobject.view_count}})</h3>
<p>{{companyobject.description}}</p>

<h3>Laptops</h3>
<div class="row">
{% for lptp in companyobject.laptop_set.all %}
 <div class="col-md-3">
<li>{{lptp.model_no}}</li>
<img src="{{lptp.image.url}}" class="img-fluid"  style="height: 200px; object-fit: cover">
<p><b>{{lptp.processor}}</b></p>

</div>
{% endfor %}
</div>
{% endblock %}

templates/companylist.html
{% extends 'base.html' %}

{% block title %}
       	Companies
		{% endblock %}

<h2>All Companies::</h2>

{% block content %}
{% for i in allcompanies %}
<!-- <b><li><a href="/company/{{i.id}}/detail/">{{i.title}}</a></li></b> -->
<b><li><a href="{% url 'photoapp:companydetail' i.pk %}">{{i.title}}</a></li></b>

{% endfor %}

{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block title %}
       	Contact
		{% endblock %}


{% block content %}
<div class="row">
	<div class="col-md-4 mx-auto">
		<h3>
			Contct Us
		</h3>
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-info">Contact</button>
		</form>
		
	</div>
	
</div>


{% endblock %}

templates/home.html
{% extends 'base.html' %}

       {% block title %}
       	Home
		{% endblock %}

{% block content %}


<div class="row">
	<div class="col-md-3">
		<li>
			<a href="/">All Laptops</a>
		</li>
		{% for company in companies %}
		<li><a href="/company/{{company.id}}/detail/">{{company.title}}</a></li>
		{% endfor %}
	</div>
	<div class="col-md-9">
		<h3>All Laptops</h3><hr>
		<div class="row">
			{% for laptop in alllaptops %}
			<div class="col-md-3">
				<h4>{{laptop.model_no}}</h4>
				<img src="{{laptop.image.url}}" class="img-fluid" style="height: 150px; object-fit: cover;">
				<p>Company:{{laptop.company.title}}</p>
				<a href="{% url 'photoapp:laptopdetail' laptop.pk %}">View Detail</a>
				<!-- <a href="/laptop/{{laptop.pk}}/detail/">View Detail</a> -->

			</div>
			{% endfor %}
		</div>

		
	</div>
</div>

{% endblock %}

templates/laptopcreate.html
{% extends 'base.html' %}



{% block content %}
<h2>Laptop Form</h2>
<div class="row">
	<div class="col-md-4 mx-auto">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-primary">Submit Data</button>
		</form>
	</div>
</div>
{% endblock %}

templates/laptopdetail.html
{% extends "base.html" %}
{% block content %}
<a href="/"><button style="color: red">Back</button></a><br>


<div class="row">
 <div class="col-md-12">
<li>{{laptopobject.company}}</li>
<li>{{laptopobject.model_no}}</li>
<img src="{{laptopobject.image.url}}" class="img-fluid"  style="height: 200px; object-fit: cover" >
<p><b>{{laptopobject.processor}}</b></p>
<p><b>{{laptopobject.description}}</b></p>
</div>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}



{% block content %}

<div class="row">
	<div class="col-md-4 mx-auto">
		<b><u>Registration Form</u></b>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-primary">Submit</button>
</form>
</div>
</div>

{% endblock %}

templates/sendmail.html
{% extends 'base.html' %}

{% block title %}
       	Mailing
		{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-4 mx-auto">
		<h3>Form</h3>
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-info">Submit</button>
		</form>
	</div>
	
</div>


{% endblock %}